// THIS FILE IS AUTO-GENERATED BY CARGO TESTS! DO NOT EDIT!

import { invoke as invokeRaw } from "@tauri-apps/api";

type TauriCommands = {
    list_conversation_titles: {
        returns: Record<string, string>,
        args: {  }
    },
    get_conversation: {
        returns: Conversation,
        args: { conversation_id: string }
    },
    get_conversation_title: {
        returns: string,
        args: { conversation_id: string }
    },
    get_conversation_messages: {
        returns: Array<ConversationMessagePayload>,
        args: { conversation_id: string }
    },
    new_conversation: {
        returns: Conversation,
        args: {  }
    },
    set_conversation_title: {
        returns: void,
        args: { conversation_id: string, new_title: string }
    },
    new_conversation_user_message: {
        returns: void,
        args: { conversation_id: string, content: string }
    },
    new_conversation_assistant_message: {
        returns: void,
        args: { conversation_id: string }
    },
    list_files: {
        returns: Array<string>,
        args: {  }
    }
};

export function invoke<T extends keyof TauriCommands>(cmd: T, args: TauriCommands[T]["args"]): Promise<TauriCommands[T]["returns"]> {
    return invokeRaw(cmd, args);
}